### ISSUE TITLE
通过python脚本的方式调用报错，请问下什么原因

### ISSUE THREAD

**Issue by seemebb** [Huawei/OpenStackClient_KMS#4]
**脚本如下：**
from keystoneauth1 import session
from keystoneauth1 import identity
from kmclient.v1 import client
auth = identity.v3.Password(auth_url=u'',
                             username=u'',
                             user_domain_id=,
                             password=u'',
                             project_name=u'eu-de',
                             project_domain_name=u'',
                             project_id=u""
                            )						 
session = session.Session(auth=auth,verify=False)
client = client.Client(session=session)
client.keys.get('5d546c30-84fb-449a-8101-2e5007c3e19d')

**报错如下：**
No handlers could be found for logger "keystoneauth.identity.base"
Traceback (most recent call last):
  File "kms_dt_test_python.py", line 23, in <module>
    client.keys.get('5d546c30-84fb-449a-8101-2e5007c3e19d')
  File "D:\git\python-kmclient\kmclient\v1\key_mgr.py", line 96, in get
    return self._create("/describe-key", json=json, key="key_info")
  File "D:\git\python-kmclient\kmclient\common\manager.py", line 100, in _create
    resp, body = self.http_client.post(url, json=json, headers=headers)
  File "C:\Python27\lib\site-packages\keystoneauth1\adapter.py", line 223, in post
    return self.request(url, 'POST', **kwargs)
  File "D:\git\python-kmclient\kmclient\common\httpclient.py", line 54, in request
    return super(OpenStackHttpClient, self).request(*args, **kwargs)
  File "C:\Python27\lib\site-packages\keystoneauth1\adapter.py", line 374, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "C:\Python27\lib\site-packages\keystoneauth1\adapter.py", line 142, in request
    return self.session.request(url, method, **kwargs)
  File "C:\Python27\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
    args, kwargs)
  File "C:\Python27\lib\site-packages\positional\__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
  File "C:\Python27\lib\site-packages\keystoneauth1\session.py", line 516, in request
    raise exceptions.EndpointNotFound()
keystoneauth1.exceptions.catalog.EndpointNotFound: Could not find requested endpoint in Service Catalog.

**Comment by IamFive** [comment]
这个是因为 workspace 的 endpoint 没有注册到 openstack，所以访问的时候，取不到Endpoint。

解决的办法有很多，
1. 在环境变量中设置 os-km-endpoint-override
2. 初始化 client 的时候，设置可选参数 endpoint
`client = client.Client(session=session, endpoint=xxxx)`

**Comment by seemebb** [comment]
Traceback (most recent call last):
  File "kms_dt_test_python.py", line 16, in <module>
    session = session.Session(auth=auth,verify=False,endpoint="https://kms.eu-de.otc.t-systems.com")
  File "C:\Python27\lib\site-packages\wrapt\wrappers.py", line 561, in __call__
    args, kwargs)
  File "C:\Python27\lib\site-packages\positional\__init__.py", line 101, in inner
    return wrapped(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'endpoint'
